/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dkSUJxp5Yi7
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function clientRegister() {
  return (
    (<div
      className="mx-auto max-w-7xl lg:grid lg:grid-cols-3 lg:gap-6 space-y-6 animate-pulse">
      <div className="col-span-3">
        <Card className="p-6">
          <CardHeader>
            <h1 className="text-3xl font-bold">Registration Form</h1>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Your Name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="company-name">Company Name</Label>
                  <Input id="company-name" placeholder="Your Company" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="organization-number">Organization Number</Label>
                  <Input id="organization-number" placeholder="123456789" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="address">Address</Label>
                  <Input id="address" placeholder="Street, City, Country" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="branch-selection">Branch Selection</Label>
                  <Input id="branch-selection" placeholder="Branch Name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="crew-number">Number of Crew</Label>
                  <Input id="crew-number" placeholder="Crew Number" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="areas">Areas</Label>
                  <Input id="areas" placeholder="Areas of Operation" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="email@example.com" required type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">Password</Label>
                  <Input id="password" required type="password" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="description">Description</Label>
                  <Textarea id="description" placeholder="Describe your company..." required />
                </div>
              </div>
              <Button className="w-full" type="submit">
                Register
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}
