/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pXXBkEyeWCz
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-64 border-r border-gray-200 dark:border-gray-800">
        <div className="flex flex-col gap-2 p-4">
          <div className="flex items-center gap-2">
            <Avatar>
              <AvatarImage alt="@shadcn" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <h2 className="text-lg font-semibold">Chats</h2>
          </div>
          <div className="grid grid-cols-[25px_1fr] items-start gap-4">
            <span className="flex h-2 w-2 translate-y-1.5 rounded-full bg-blue-500" />
            <div className="grid gap-1">
              <p className="text-sm font-medium">John Doe</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Hello, how are you?</p>
              <p className="text-xs text-gray-400 dark:text-gray-300">10:00 AM</p>
            </div>
          </div>
          <div className="grid grid-cols-[25px_1fr] items-start gap-4">
            <span className="flex h-2 w-2 translate-y-1.5 rounded-full bg-blue-500" />
            <div className="grid gap-1">
              <p className="text-sm font-medium">Jane Smith</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">I'm good, thanks!</p>
              <p className="text-xs text-gray-400 dark:text-gray-300">10:05 AM</p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col flex-1">
        <div
          className="flex items-center gap-2 p-4 border-b border-gray-200 dark:border-gray-800">
          <Avatar>
            <AvatarImage alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
          <h2 className="text-lg font-semibold">John Doe</h2>
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          <div className="flex items-end justify-end">
            <div
              className="max-w-[75%] bg-blue-500 text-white rounded-br-none rounded-bl-none rounded-r-md p-2">
              Hello, how are you?
            </div>
          </div>
          <div className="flex items-start justify-start">
            <div
              className="max-w-[75%] bg-gray-100 dark:bg-gray-800 rounded-bl-none rounded-br-none rounded-l-md p-2">
              I'm good, thanks!
            </div>
          </div>
        </div>
        <div
          className="flex items-center gap-2 p-4 border-t border-gray-200 dark:border-gray-800">
          <Input className="flex-1" placeholder="Type a message" />
          <Button variant="outline">Send</Button>
        </div>
      </div>
    </div>)
  );
}
