/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EYl41RqAT4Z
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { CommandInput, CommandEmpty, CommandItem, CommandGroup, Command } from "@/components/ui/command"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Component() {
  return (
    (<main key="1" className="space-y-8">
      <Card>
        <CardHeader className="font-bold text-lg">Add New Mission</CardHeader>
        <CardContent className="grid gap-4">
          <Popover className="space-y-2">
            <PopoverTrigger asChild>
              <Button className="w-full justify-between" role="combobox" variant="outline">
                Select Job Category...
                <ChevronsUpDownIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-full p-0">
              <Command>
                <CommandInput className="h-9" placeholder="Search job category..." />
                <CommandEmpty>No job category found.</CommandEmpty>
                <CommandGroup>
                  <CommandItem>Category 1</CommandItem>
                  <CommandItem>Category 2</CommandItem>
                  <CommandItem>Category 3</CommandItem>
                  <CommandItem>Category 4</CommandItem>
                </CommandGroup>
              </Command>
            </PopoverContent>
          </Popover>
          <Popover className="space-y-2">
            <PopoverTrigger asChild>
              <Button className="w-full justify-between" role="combobox" variant="outline">
                Select Job Title...
                <ChevronsUpDownIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-full p-0">
              <Command>
                <CommandInput className="h-9" placeholder="Search job title..." />
                <CommandEmpty>No job title found.</CommandEmpty>
                <CommandGroup>
                  <CommandItem>Title 1</CommandItem>
                  <CommandItem>Title 2</CommandItem>
                  <CommandItem>Title 3</CommandItem>
                  <CommandItem>Title 4</CommandItem>
                </CommandGroup>
              </Command>
            </PopoverContent>
          </Popover>
          <div className="grid gap-1.5">
            <Label htmlFor="people-needed">Number of People Needed</Label>
            <Input
              id="people-needed"
              placeholder="Enter number of people needed"
              type="number" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="start-date">Start Date</Label>
              <Input id="start-date" type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="end-date">End Date</Label>
              <Input id="end-date" type="date" />
            </div>
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="hours">Hours</Label>
            <Input id="hours" placeholder="Enter hours required" type="number" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="address">Address</Label>
            <Input id="address" placeholder="Enter mission location" type="text" />
          </div>
          <Button className="w-full bg-blue-500 text-white" type="submit">
            Add Mission
          </Button>
        </CardContent>
      </Card>
    </main>)
  );
}


function ChevronsUpDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m7 15 5 5 5-5" />
      <path d="m7 9 5-5 5 5" />
    </svg>)
  );
}
